### ISSUE TITLE
IEx on UART, line wrapping problems if terminal emulator not exactly 80 columns

### ISSUE THREAD

**Issue by troygnichols** [nerves-project/nerves_runtime#22] opened 2017-06-26 01:14 UTC
When I'm connected to my nerves device over a UART using GNU screen, if I resize the terminal emulator (iTerm or Terminal.app), IEx does not wrap lines properly for the new screen size. It seems to still think columns are 80 characters.

![nerves-iex-uart-tty-weird 1](https://user-images.githubusercontent.com/221013/27521436-07d5ad06-59eb-11e7-863b-d49082b4b231.gif)

**Comment by GregMefford** [comment] 2017-07-05 14:18
Thanks for making a GH issue for this so we don't lose track! 🚀 

To clarify the situation: you're just using `screen` to connect to the UART pins on your target device and interacting with the `iex` shell that comes up automatically during the boot process, correct?

My initial guess is either that `screen` isn't passing through window-size information, or the Elixir/`iex` process isn't interpreting them. Just to help narrow down the issue, have you seen this work correctly for other devices in the past and this was a surprise, or is this normal behavior that you'd like to be solved by Nerves somehow?

**Comment by troygnichols** [comment] 2017-07-05 17:57
> you're just using screen to connect to the UART pins on your target device and interacting with the iex shell that comes up automatically during the boot process, correct?

Yep that's correct

> have you seen this work correctly for other devices in the past and this was a surprise

I haven't seen it work correctly on any device. I've tested it on a raspberry pi and a nanopi neo.

> is this normal behavior that you'd like to be solved by Nerves somehow?

Yeah, I suppose it's a "normal" behavior that it would be nice if nerves could correct somehow. Or maybe it's a matter of configuring `screen` differently.

**Comment by fhunleth** [comment] 2017-07-18 20:56
A few notes:

1. When not using a serial port, terminal resizes are communicated via a WINCH signal and the TIOCGWINSZ ioctl. Those don't work over a serial connection, but there is a VT102 (not sure if VT102 or a later spec) does have control codes to communicate window size.
2. Quick google search says that `IO.write(<<0x1b, "[18t">>)` triggers the window size to be sent back. I got `;46;121t` back when I tried it. My terminal is 46 rows and 121 columns
3. Somehow that information needs to be parsed and sent to the TIOCSWINSZ ioctl. That would get it into Erlang's code. Erlang has a WINCH handler and it calls the TIOCGWINSZ ioctl to get the new window size.
4. The code that handles the window size escape code and its response could be shimmed in via the `-s` parameter in the `erlinit.config`. I looked at using `dtach` and `tmux` to do this, but neither of them appear to support the VT100 window size escape sequence.

**Comment by fhunleth** [comment] 2017-10-08 23:19
I may have made some progress on this bug on accident:

Here's a video my current status (there is a bug if you look carefully):
https://youtu.be/g0vEYNdv2J0

This is done with https://github.com/fhunleth/nbtty. The program intercepts the data going through the tty. It sends an ANSI sequence to figure out the window size and looks for the response. When it sees the response, it updates the window size that Erlang and Elixir see. 

The `nbtty` program isn't in a form to be merged yet and was intended for a different purpose, but I figured that I'd report my progress.

**Comment by fhunleth** [comment] 2017-10-12 13:39
I've updated `nbtty` and it seems to be working fairly well. Resize changes get detected when after newlines to avoid querying all the time.

I need to clean up `nbtty` some more before I feel good about integrating it. If I can make it small enough, I might try to combine it with `erlinit` at some point in the future.

**Comment by fhunleth** [comment] 2018-07-05 13:38
Closing since `nbtty` support for reacting to window size changes was integrated in `nbtty v0.2.0` and some improvements were added afterwards. Everyone should have them now.

**Closed by fhunleth** 2018-07-05 13:38 UTC
Labels: enhancement, help wanted
